disallowed-blocks:
  - shulker
  - infesteD
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - BEDROCK
  - BARRIER
  - END_PORTAL_FRAME
  - END_PORTAL
  - END_GATEWAY
  - CRYING_OBSIDIAN
  - OBSIDIAN
  - JIGSAW
  - RESPAWN_ANCHOR
  - TEST_INSTANCE_BLOCK
  - TEST_BLOCK