# - What height the random layer chunk will begin at (default: 250)
startheightY: 250

# - Which blocks to disallow. Use custom flags "shulker" and or "infested" to disallow all flavors of said block
disallowed-blocks:
  - SHULKER
  - INFESTED
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - BEDROCK
  - BARRIER
  - END_PORTAL_FRAME
  - END_PORTAL
  - END_GATEWAY
  - CRYING_OBSIDIAN
  - OBSIDIAN
  - JIGSAW
  - RESPAWN_ANCHOR
  - TEST_INSTANCE_BLOCK
  - TEST_BLOCK