name: RandomLayerChunk
version: '1.0-SNAPSHOT'
main: me.colt.randomLayerChunk.RandomLayerChunk
api-version: '1.20'
load: STARTUP
commands:
  clearchunk:
    description: "yo"
    usage: "/clearchunk"
  rlc:
    description: "rlcea"
    usage: "/rlc"